"use client";

// The club's REAL research record. The JSON is generated by Python
// (export_track_record.py) from the same engines that produced the verdicts,
// and committed to the repo — so this section is honest even when the live
// backend is asleep or has no vendor data.
import record from "@/lib/track_record.json";
import { pct, num } from "@/lib/api";

const ws = record.wide_scan;
const th = record.thesis_001;

export function TrackRecord() {
  return (
    <div style={{ marginTop: 12 }}>
      <div className="sm-card" style={{ marginBottom: 12 }}>
        <div className="sm-card-h">
          The track record — what we&apos;ve actually tested
          <span>real data · walk-forward OOS · net of costs · generated {record.generated}</span>
        </div>

        <p className="muted" style={{ margin: "0 0 10px", fontSize: 12.5, lineHeight: 1.55 }}>
          <b style={{ color: "var(--text-primary)" }}>
            {ws.n_backtests} walk-forward backtests across {ws.n_tickers} liquid names
            ({ws.strategies.join(", ")}): {ws.edges} clean edges.
          </b>{" "}
          {ws.suspects} looked interesting but failed at least one honesty gate
          (too few trades, one-year wonder, or best-of-N luck); {ws.dead} were simply dead.
          That is the honest base rate — on daily bars, simple timing rules do not beat
          holding the index. The machine&apos;s job is to refuse fake winners, and it does.
        </p>

        <table>
          <thead>
            <tr>
              <th>Ticker / strategy</th><th>OOS return</th><th>Sharpe</th>
              <th>Trades/fold</th><th>Verdict</th>
            </tr>
          </thead>
          <tbody>
            {ws.top.slice(0, 6).map((r, i) => (
              <tr key={i}>
                <td>{r.ticker} / {r.strategy}</td>
                <td className={r.oos_return >= 0 ? "good" : "bad"}>{pct(r.oos_return)}</td>
                <td>{num(r.sharpe)}</td>
                <td>{r.trades_per_fold.toFixed(1)}</td>
                <td className={r.verdict === "EDGE?" ? "good" : "bad"}>{r.verdict}</td>
              </tr>
            ))}
          </tbody>
        </table>
        <p className="tertiary" style={{ margin: "8px 0 0", fontSize: 11 }}>
          Top raw returns shown for context — big numbers with a &quot;dead/suspect&quot; verdict are
          exactly the trap: few trades per fold, 2020-concentrated, or indistinguishable from
          best-of-{ws.n_backtests} luck after the deflated-Sharpe discount.
        </p>
      </div>

      <div className="sm-card">
        <div className="sm-card-h">
          Thesis 001 — cross-sectional momentum (the first reasoned strategy)
          <span>{th.window[0]} → {th.window[1]}</span>
        </div>
        <div className={`sm-badge ${th.status.startsWith("SURVIVES") ? "sm-live" : "sm-dead"}`}
          style={{ marginBottom: 8 }}>
          {th.status.startsWith("SURVIVES") ? "SURVIVES FIRST TEST" : "KILLED"}
        </div>
        <p className="muted" style={{ margin: "0 0 10px", fontSize: 12.5, lineHeight: 1.55 }}>
          {th.spec}. Economic story: intermediate-horizon winners keep winning
          (Jegadeesh–Titman 1993). The bar it had to clear: beat equal-weighting the
          <em> same universe</em> (selection skill, not survivorship), random picks, and SPY —
          all through identical dates and costs.
        </p>
        <table>
          <thead>
            <tr><th>Portfolio</th><th>Total return</th><th>CAGR</th><th>Sharpe</th><th>Max DD</th></tr>
          </thead>
          <tbody>
            <Row label="Momentum top-10" m={th.momentum} strong />
            <Row label="EW universe (all names)" m={th.ew_universe} />
            {th.spy && <Row label="Hold SPY" m={th.spy} />}
          </tbody>
        </table>
        <p className="muted" style={{ margin: "10px 0 0", fontSize: 11.5, lineHeight: 1.5 }}>
          Beat the universe in {th.per_year.filter((y) => y.ew_universe != null && y.momentum > y.ew_universe).length} of{" "}
          {th.per_year.length} years, including the 2022 drawdown
          ({pct(th.per_year.find((y) => y.year === 2022)?.momentum ?? null)} vs{" "}
          {pct(th.per_year.find((y) => y.year === 2022)?.ew_universe ?? null)}).
          Status: <b>{th.status}</b>. Caveats: {th.caveats.join("; ")}.
        </p>

        <div style={{ marginTop: 12, paddingTop: 10, borderTop: "1px solid var(--border)" }}>
          <div style={{ fontSize: 12, fontWeight: 600, marginBottom: 6, color: "var(--text-primary)" }}>
            Robustness gauntlet — the same skeptic&apos;s checks the wide scan applies
          </div>
          <div style={{ display: "flex", gap: 18, flexWrap: "wrap", fontSize: 12, marginBottom: 10 }}>
            <span className="muted">
              Probabilistic Sharpe (monthly):{" "}
              <b className={th.probabilistic_sharpe >= 0.95 ? "good" : "bad"}>{num(th.probabilistic_sharpe)}</b>
            </span>
            {th.regime_split && (
              <span className="muted">
                By SPY regime — up <b className="good">{pct(th.regime_split.up.return)}</b>,{" "}
                down {pct(th.regime_split.down.return)},{" "}
                chop <b className="bad">{pct(th.regime_split.chop.return)}</b>
              </span>
            )}
          </div>

          <p className="muted" style={{ margin: "0 0 6px", fontSize: 11.5, lineHeight: 1.5 }}>
            Sensitivity —{" "}
            <b style={{ color: "var(--text-primary)" }}>{th.sweep_beats_ew} neighbor specs beat their EW-universe</b>.
            We do <em>not</em> select the best; the pre-registered 12mo/top-10 stays the verdict.
            A broad neighborhood means the edge is not a single lucky config.
          </p>
          <table>
            <thead>
              <tr><th>Lookback</th><th>Top N</th><th>Total return</th><th>Sharpe</th><th>Beats EW</th></tr>
            </thead>
            <tbody>
              {th.sweep.map((s, i) => (
                <tr key={i} style={s.canonical ? { fontWeight: 600 } : undefined}>
                  <td>{s.lookback}{s.canonical ? " ★" : ""}</td>
                  <td>{s.top_n}</td>
                  <td className={s.total_return >= 0 ? "good" : "bad"}>{pct(s.total_return)}</td>
                  <td>{num(s.sharpe)}</td>
                  <td className={s.beats_ew ? "good" : "bad"}>{s.beats_ew ? "YES" : "no"}</td>
                </tr>
              ))}
            </tbody>
          </table>

          {th.red_flags.length > 0 && (
            <div style={{
              marginTop: 10, padding: "8px 10px", borderRadius: 6, fontSize: 11.5,
              background: "rgba(220,38,38,0.08)", border: "1px solid rgba(220,38,38,0.25)",
            }}>
              <b className="bad">Red flag{th.red_flags.length > 1 ? "s" : ""}:</b>{" "}
              {th.red_flags.join(" ")}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function Row({ label, m, strong }: {
  label: string;
  m: { total_return: number; cagr: number; sharpe: number; max_dd: number };
  strong?: boolean;
}) {
  return (
    <tr style={strong ? { fontWeight: 600 } : undefined}>
      <td>{label}</td>
      <td className={m.total_return >= 0 ? "good" : "bad"}>{pct(m.total_return)}</td>
      <td>{pct(m.cagr)}</td>
      <td>{num(m.sharpe)}</td>
      <td className="bad">{pct(m.max_dd)}</td>
    </tr>
  );
}
